[package]
name = "rtherm"
version = "0.1.0"
edition = "2021"

description = "RTherm server"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
rtherm-common = { workspace = true }
