[package]
name = "rtherm"
version = "0.1.0"
edition = "2021"

description = "RTherm server"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
sqlite = []

[dependencies]
rtherm-common = { workspace = true }
actix-web = "4"
actix-files = "0.6.2"
